drop table users cascade;
drop table wallet cascade;
drop table password cascade;
drop table car cascade;
drop table owns cascade;
drop table payer cascade;
drop table parking_mall cascade;
drop table parking_floor cascade;
drop table parks cascade;
drop table notifications;
